### ISSUE TITLE
[ReactWidget] Lage validering av donation state, sørg for at endringer i shares oppdaterer state

### ISSUE THREAD

**Issue by fellmirr** [stiftelsen-effekt/effekt-widget-react#19]
- [x] Endringer i shares oppdaterer state
- [x] Validering av donation input

**Comment by fellmirr** [comment]
@philiphand Jeg har lagt til litt enkel validering i bonn av donationreducer og fikset shares ifb. at jeg lagde en ny input komponent.

**Comment by philiphand** [comment]
Ok, herlig!
