### ISSUE TITLE
Lage skjema på nettsiden og DB for FB-skattefradrag

### ISSUE THREAD

**Issue by Mofoss** [stiftelsen-effekt/effekt-widget-react#34]
**KORT:** 
**_Vi trenger en kopi av widgeten / et eget registreringsskjema for å registrere givere som har donert via Facebook, som lagrer deres Betalings-ID fra Facebook i databasen vår på eksisterende bruker eller også oppretter en ny bruker for dem (user-ID). Dette haster ikke, men må senest være klart før giversesongen 2021._**

**LANG:**
Vi har i dag et [Google Form](https://docs.google.com/forms/d/e/1FAIpQLScTvffvskQXvxG_72D3LqrfICNbYyLx--_69wjUhbu430rYFQ/viewform) som vi bruker til å registrere donasjoner for skattefradrag gjort gjennom Facebook, ettersom de ofte ikke har donert gjennom nettsiden vår før og dermed oppgitt sitt fødselsnummer til oss eller fått noen "bruker" hos oss. Uansett kan vi ofte ikke matche FB-donasjoner fra eksisterende givere med deres data, ettersom FB nesten aldri gir oss e-postadressene deres (med mindre de aktivt tillater det), og navnene kan være annerledes (mellomnavn, vanlige navn vi har duplikater av, osv.).

Vi trenger dette av to grunner. 
1) Det er ikke så pent og tillitsfullt at vi bruker Google Forms, og 
2) det hadde vært bedre å få registrert giverne direkte i systemet vårt. 

Derfor skulle vi helst brukt vår vanlige widget, men med en "twist", der givere også må registrere en Betalings-ID fra en av sine FB-donasjoner gjennom oss. Så lenge vi får den minst en gang, så kan vi koble en donasjon til deres FB-bruker, og da også alle andre (da vet vi deres FB-navn og kan finne resten. Med en liten fare for at andre personer med nøyaktig samme navn også har donert gjennom FB, som i så fall gir dem ekstra skattefradrag. Men alternativet er at vi ber om betalings-ID for alle donasjoner, og det er litt tungvint).

Jeg foreslår vi lager en egen tabell i databasen for "fb_betalingsid", eller noe sånt, hvor vi for alle user-IDs som registrerer seg i skjemaet lagrer deres betalings-ID (en eller flere ganger). Hvis brukeren allerede eksisterer i databasen (deres epostadresse), så trenger vi ikke spørre om fnr på nytt, bare betalings-ID. Så første side av skjemaet tenker jeg kan være bare epost + betalingsID. Neste side kan være navn og fnr (hvis ikke epost og fnr allerede er registrert).

Informasjonstekst til registreringen kan hentes fra Google Form-skjemaet (se lenke ovenfor), og Redningsselskapet sin registrering kan også være til inspirasjon (se [videogjennomgang her](https://business.facebook.com/watch/?v=2658716364355420&__cft__[0]=AZVdHT7MDzNIMO5_qXoqoyvypWXKbm4FqW0ZSvpS7dHnRBbHKdvzENVDKScYymuDkY-kPcw6Xet4tQaF_HWnP6y8cK36ZX1OLtLOFERYPLuHSYy4pHXEcdRMeTYzFhFDakWwUyn24YC28Wqkjyo5Brxmoc50H1TvKE0S5JO5Mg1jnLiUlDo5XT149y7mdCzIr0E&__tn__=-UK*F)).

**Comment by philiphand** [comment]
Skal vi tillate 9-sifret organisasjonsnummer i dette skjemaet også, eller kun 11-sifret personnummer?

**Comment by Mofoss** [comment]
Jeg ser ikke helt for meg at en bedrift skal donere gjennom FB, og det vil jo uansett dukke opp som en donasjon fra privatpersonen (som gjør det). Så jeg tenker at kun 11 siffer bør aksepteres.

**Comment by philiphand** [comment]
Virker ikke som at det finnes en måte som gjør skjemaet dynamisk 1- eller 2-stegs uten å eksponere en måte for folk å sjekke om epost-adresser er registrert hos oss. Den letteste måten å forhindre det er å ha hele skjemaet på én side med alle 4 input-feltene, så håndterer vi heller all dataen i backend og registrerer en ny bruker om den ikke finnes fra før. For eksisterende brukere (de med registrert email) oppdaterer vi da kun personnummer hvis det mangler (ellers kan folk bruke skjemaet til å endre andres personnummer).
